### PR TITLE
[add] installation video playlist embed

### PR DESCRIPTION
**Pull request by lennart**
video-installation

### CODE REVIEW

**Comment by sfradkin** [comment]
I was thinking that we could have a heading for install videos.  Also I think we want to modify the Mac install instructions to match the video since it simplifies things greatly.

**Comment by lennart** [comment]
@sfradkin the transcript is posted in slack right? 

regarding a separate headline for the installation videos: I consider the videos part of our installation documentation and it is just one video embed for all platforms (a playlist), so effectively we would end up with a headline, maybe one sentence of text and a video embed. since this should be one of the first things people should see would be the videos I see no benefit for users to have an additional Video installation/guide headline/menu link. Am I misunderstanding, what you were up to?

**Comment by sfradkin** [comment]
I was just thinking of a section heading that says 'Installation Videos' then a line something like: 'Click on the embedded video playlist to view installation for MacOS. Videos forthcoming for Windows and Linux.' Then the embed.  Nothing fancy.

**Comment by yaxu** [comment]
Have merged for now but agree this needs some structure. Actually I think we need to separate out install instructions per platform again.

**Pull request merged**
