### PR TITLE
Brand identity

### PR DESCRIPTION
**Pull request by lennart**
This will use TidalCycles brand guidelines and consolidate overall looking and usability of the website.

Identity changes:

- use colour palette and tints for highlighting and gradient (replaces image on Home, less bandwidth!).
- use Roboto Condensed for body/headings

Structural changes:

Credits move to footer menu to avoid navigation overload (we might need to refactor our information architecture here!)
This is achieved via the `footer: true` flag in `_data/chapters.yml`

Bugfixes:

- Home layout is more adaptive
  - video/text float side-by-side on desktop
  - only first parapraph is `.lead` we have lots of content now (maybe refactor here as well)
- blockquotes `overflow-x: auto` now to avoid broken navigation on mobile

Since reading html and css changes, see some screenshots of Home, Installation and Credits in the new brand identity:

tidal-home-320x568
---
tidal-home-768x1024
---
tidal-home-1280x800
---
tidal-home-1920x1080
---
tidal-install-320x568
---
tidal-install-768x1024
---
tidal-install-1280x800
---
tidal-install-1920x1080
---
tidal-credits-320x568
---
tidal-credits-768x1024
---
tidal-credits-1280x800
---
tidal-credits-1920x1080

### CODE REVIEW

**Comment by yaxu** [comment]
Looks very nice indeed! How about adding a small logo on the non-front pages?

**Comment by lennart** [comment]
I tried around with this idea but didn't finish, is this a "merge stopper", @yaxu ?

otherwise I'd let this update settle and add in a small logo afterwards (but before we merge into tidalcycles.org)

**Comment by yaxu** [comment]
Please do merge!

**Comment by sfradkin** [comment]
I like it!  And also agree that having a small logo on the other pages would be nice.  I can't imagine we should wait for a merge on that though.

**Pull request merged**
